version: '3'

services:
  qq:
    # build: 
    #   context: .
    #   args:
    #     USER_ID: ${USER_ID}
    #     TIMEZONE: ${TIMEZONE}
    image: ntdgy2001/linux-qq
    environment:
      - LANG=zh_CN.UTF-8
      - GTK_IM_MODULE=fcitx
      - XMODIFIERS=@im=fcitx
      - DBUS_SESSION_BUS_ADDRESS=unix:path=${USER_DBUS_SESSION_BUS_ADDRESS}
      - PULSE_SERVER=unix:${USER_PULSE_SERVER}
      - DISPLAY
      - XAUTHORITY=/home/user/.Xauthority
    volumes:
      - "${USER_HOME}/.Xauthority:/home/user/.Xauthority:ro"
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      # - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - "${USER_DBUS_SESSION_BUS_ADDRESS}:${USER_DBUS_SESSION_BUS_ADDRESS}"
      - "${USER_PULSE_SERVER}:${USER_PULSE_SERVER}"
      - "./QQ/:/home/user/.config/QQ/"
      - "./shared/:/home/user/shared/"
    hostname: ${HOSTNAME}
    command: 'linuxqq --no-sandbox'
    shm_size: 2gb
    devices:
      - /dev/dri/card0
networks:
  dc-oa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1
