name: build docker

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      test:
        required: false
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Version
        id: version_step
        run: |
          # get commit hash
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: BuildDockerImage
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ntdgy2001/linux-qq:latest
            ntdgy2001/linux-qq:${{ env.COMMIT_HASH }}
            ghcr.io/super-moe/linux-qq:latest
            ghcr.io/super-moe/linux-qq:${{ env.COMMIT_HASH }}
          file: ./Dockerfile
    
